[build]
  publish = "public"
  command = "yarn install && yarn build"
[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
     Referrer-Policy = "strict-origin-when-cross-origin"
[[headers]]
  for = "/fonts/*"
    [headers.values]
     Access-Control-Allow-Origin = "*"
